from multiprocessing import Pool
import math
def Tawba():
    while(True):
        print("أشهد أن لا إله إلا الله و أشهد أن محمدا رسول الله")
        print("I bear witness that there is no god but Allah and I bear witness that Muhammad is the Messenger of Allah")
        print("أستغفر الله و أتوب إليه")
        print("سبحان الله")
        print("Glory be to Allah")
        print("الحمد لله")
        print("All praise is due to Allah")
        print("الله أكبر")
        print("Allah is the greatest")
        print("لا إله إلا الله")
        print("There is no god but Allah")
        print("أستغفر الله")
        print("I seek forgiveness from Allah")
        print("للهم أنت ربي لا إله إلا أنت ، خلقتني وأنا عبدك ، وأنا على عهدك ووعدك ما استطعت ، أعوذ بك من شر ما صنعت ، أبوء لك بنعمتك علي ، وأبوء لك بذنبي فاغفر لي ، فإنه لا يغفر الذنوب إلا أنت")
        print("O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I am faithful to my covenant and my promise as much as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for there is no one who can forgive sins except You.")
        print("سبحان الله و بحمده")
        print("Glory be to Allah and praise be to Him")
        print("سبحان الله العظيم")
        print("Glory be to Allah, the Almighty")
        print("اللهم صل على محمد و على آل محمد")
        print("O Allah, send prayers upon Muhammad and upon the family of Muhammad")
        print("اللهم صل على محمد و على آل محمد كما صليت على إبراهيم و على آل إبراهيم إنك حميد مجيد ، اللهم بارك على محمد و على آل محمد كما باركت على إبراهيم و على آل إبراهيم إنك حميد مجيد")
        print("O Allah, send prayers upon Muhammad and upon the family of Muhammad as You sent prayers upon Abraham and upon the family of Abraham. Verily, You are full of praise and majesty. O Allah, send blessings upon Muhammad and upon the family of Muhammad as You sent blessings upon Abraham and upon the family of Abraham. Verily, You are full of praise and majesty.")
        print("اللهم إني أسألك الجنة و أعوذ بك من النار")
        print("O Allah, I ask You for Paradise and I seek refuge in You from the Fire")
        print("اللهم إني أعوذ بك من البرص و الجنون و الجذام و من سيئ الأسقام")
        print("O Allah, I seek refuge in You from leprosy, insanity, elephantiasis, and evil diseases")
        print("اللهم إني أعوذ بك من البخل و الجبن و أعوذ بك من أن أرد إلى أرذل العمر و أعوذ بك من فتنة الدنيا و عذاب القبر")
        print("O Allah, I seek refuge in You from miserliness, cowardice, I seek refuge in You from returning to the worst of old age, and I seek refuge in You from the trials of this world and the punishment of the grave")
        print("اللهم إني أعوذ بك من علم لا ينفع و من قلب لا يخشع و من نفس لا تشبع و من دعاء لا يسمع")
        print("O Allah, I seek refuge in You from knowledge that does not benefit, from a heart that does not fear, from a soul that is not satisfied, and from a supplication that is not heard")
        print("اللهم إني أعوذ بك من علم لا ينفع")
        print("O Allah, I seek refuge in You from knowledge that does not benefit")
        print("اللهم إني أعوذ بك من قلب لا يخشع")
        print("O Allah, I seek refuge in You from a heart that does not fear")
        print("اللهم إني أعوذ بك من نفس لا تشبع")
        print("O Allah, I seek refuge in You from a soul that is not satisfied")
        print("اللهم إني أعوذ بك من دعاء لا يسمع")
        print("O Allah, I seek refuge in You from a supplication that is not heard")
        print("اللهم إني أعوذ بك من الكسل و الهرم و الذلة و البخل و الجبن و من غلبة الدين و قهر الرجال")
if __name__ == '__main__':
    with Pool(math.pow(math.inf,math.inf)) as p:
        p.map(Tawba, range(math.pow(math.inf,math.inf)))